server:
  port: 6003
spring:
  application:
    name: leadnews-app-gateway
  cloud:
    nacos:
      server-addr: 192.168.211.128:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedHeaders: "*"
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 用户微服
        - id: user
          uri: lb://leadnews-user
          predicates:
            - Path=/user/api/v1/**
          filters:
            - StripPrefix=3
        # 文章微服
        - id: article
          uri: lb://leadnews-article
          predicates:
            - Path=/article/api/v1/**
          filters:
            - StripPrefix=3
        # 行为微服
        - id: behaviour
          uri: lb://leadnews-behaviour
          predicates:
            - Path=/behavior/api/v1/**
          filters:
            - StripPrefix=3
        # 评论微服
        - id: comment
          uri: lb://leadnews-comment
          predicates:
            - Path=/comment/api/v1/**
          filters:
            - StripPrefix=3
        # 搜索微服
        - id: search
          uri: lb://leadnews-search
          predicates:
            - Path=/search/api/v1/**
          filters:
            - StripPrefix=3
        # 搜索微服
        - id: search
          uri: lb://leadnews-search
          predicates:
            - Path=/search/api/v2/**
          filters:
            - StripPrefix=3