server:
  port: 9005
spring:
  application:
    name: leadnews-dfs
  cloud:
    nacos:
      server-addr: 192.168.211.128:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# fastdfs的配置
fdfs:
  so-timeout: 15001
  connect-timeout: 6001
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 192.168.211.128:22122 #TrackerList参数,支持多个
  web-server-url: http://192.168.211.128/  # 设置前缀路径