server:
  port: 9002
spring:
  application:
    name: leadnews-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/leadnews_user?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
  cloud:
    nacos:
      server-addr: 192.168.211.128:8848

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
steven:
  knife4j:
    description: 头条项目用户微服务api
    title: 头条项目用户微服务api
    contact: leadnews
    serviceUrl: