server:
  port: 9006
spring:
  profiles: dev
  application:
    name: leadnews-behaviour
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.128:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/leadnews_behaviour?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
  kafka:
    # 配置连接到服务端集群的配置项 ip:port,ip:port
    bootstrapServers: 192.168.211.128:9092
    consumer:
      auto-offset-reset: earliest
      group-id: behaviour-consumer-group
      # 默认值即为字符串
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 默认值即为字符串
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # 行为微服务处理的评论、阅读、喜欢不喜欢等行为，需要发消息给kafka流处理器，由流处理器聚合分析，发送给消费者，消费者更新并为下游推荐评分重新计算
    producer:
      batchSize: 16384
      bufferMemory: 33554432
      retries: 10
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.leadnews.behaviour.pojo
  global-config:
    datacenter-id: 0
    worker-id: 2