server:
  port: 9007
spring:
  application:
    name: leadnews-comment
  cloud:
    nacos:
      server-addr: 192.168.211.128:8848
  data:
    mongodb:
      host: 192.168.211.128
      port: 27017
      database: leadnews-comment