server:
  port: 9004
spring:
  application:
    name: leadnews-wemedia
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/leadnews_wemedia?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
  cloud:
    nacos:
      server-addr: 192.168.211.128:8848
  redis:
    host: 192.168.211.128
    port: 6379
  kafka:
    producer:
      # 配置连接到服务端集群的配置项 ip:port,ip:port
      bootstrap-servers: 192.168.211.128:9092
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 10
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
steven:
  knife4j:
    description: 头条项目自媒体微服务api
    title: 头条项目自媒体微服务api
    contact: leadnews
    serviceUrl:

# 注意缩进，最左边的
fastdfs-server: http://192.168.211.128/